CREATE SCHEMA NOTA_FISCAL;

USE NOTA_FISCAL;

CREATE TABLE NOTA_FISCAL (
	NRO_NOTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    END_CLIENTE VARCHAR(100) NOT NULL,
    NOME_VENDEDOR VARCHAR(100) NOT NULL,
    DT_EMISSAO TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    VL_TOTAL_NOTA DECIMAL(9, 2) NOT NULL
);

CREATE TABLE ITEM_NOTA_FISCAL (
	NRO_NOTA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    DESC_PRODUTO VARCHAR(255),
    QTD_PRODUTO INT NOT NULL,
    VL_PRODUTO DECIMAL(9, 2) NOT NULL,
    VL_TOTAL DECIMAL(9, 2) NOT NULL,
    PRIMARY KEY (NRO_NOTA, ID_PRODUTO),
    FOREIGN KEY (NRO_NOTA) REFERENCES NOTA_FISCAL(NRO_NOTA)
);