CREATE DATABASE FORMULARIO;

USE FORMULARIO;

CREATE TABLE FUNCIONARIO(
	MATRICULA CHAR(10) NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DT_NASC DATETIME NOT NULL,
    NACIONALIDADE VARCHAR(50) NOT NULL,
    SEXO CHAR NOT NULL,
    EST_CIVIL VARCHAR(20) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL
);

CREATE TABLE CARGO(
	MATRICULA CHAR(10) NOT NULL,
    CARGO VARCHAR(100) NOT NULL,
    DT_INICIO DATETIME NOT NULL,
    DT_FIM DATETIME,
    CONSTRAINT FK_MATRICULA_FUNCIONARIO FOREIGN KEY (MATRICULA) REFERENCES FUNCIONARIO(MATRICULA)
);

CREATE TABLE DEPARTAMENTO(
	MATRICULA CHAR(10) NOT NULL,
	DEPARTAMENTO VARCHAR(100),
    DT_INICIO DATETIME NOT NULL,
    DT_FIM DATETIME,
    CONSTRAINT FK_MATRICULA_DPTO_FUNCIONARIO FOREIGN KEY (MATRICULA) REFERENCES FUNCIONARIO(MATRICULA)
);

CREATE TABLE DEPENDENTE(
	MATRICULA CHAR(10) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
    DT_NASC DATETIME NOT NULL,
    CONSTRAINT FK_MATRICULA_DEP_FUNCIONARIO FOREIGN KEY (MATRICULA) REFERENCES FUNCIONARIO(MATRICULA)
);