/* SELECIONANDO AERONAVES E ORDENANDO POR TIPO */
CALL GetAllPlanes();

/* LISTAGEM DE VÔOS POR PERÍODO */
CALL GetFlightsBetweenDates('2024-05-01', '2024-05-31');

/* LISTAGEM DE VÔOS QUE FAZEM ESCALA EM UM DETERMINADO LOCAL */
CALL GetFlightsByScales(4);

/* EXIBINDO ASSENTOS LIVRES EM UM DETERMINADO VOO */
CALL GetFreeSeatsByFlightId(3);

CALL GetAllFlights();