DROP SCHEMA `SIS2402`;
CREATE SCHEMA `SIS2402`;
CREATE TABLE `SIS2402`.`CLIENTES`(
	`NAME` VARCHAR(20) NOT NULL,
    `EMAIL` VARCHAR(254) NOT NULL PRIMARY KEY,
    `BIRTH_DATE` DATE NOT NULL,
    `GENDER` CHAR NOT NULL,
    `ZIP_CODE` INT NOT NULL,
    `STREET` VARCHAR(20) NOT NULL,
    `NUMBER` INT NOT NULL,
    `DISTRICT` VARCHAR(15) NOT NULL,
    `CITY` VARCHAR(12) NOT NULL,
    `STATE` CHAR(2) NOT NULL,
    `COUNTRY` VARCHAR(12) NOT NULL
);
