CREATE DATABASE RELACIONANDO_IMOVEL;

USE RELACIONANDO_IMOVEL;

CREATE TABLE TP_CATEGORIA (
    ID_Categoria INT AUTO_INCREMENT PRIMARY KEY,
    Nome_Categoria VARCHAR(255)
);

CREATE TABLE TP_LOCALIDADE (
    ID_Localidade INT AUTO_INCREMENT PRIMARY KEY,
    Tp_Localidade VARCHAR(50)
);

CREATE TABLE TP_VENDA (
    ID_Venda INT AUTO_INCREMENT PRIMARY KEY,
    Tp_Negocio VARCHAR(50)
);

CREATE TABLE ITENS (
    ID_Item INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(255),
    Descricao TEXT,
    Valor DECIMAL(10, 2),
    Nro_de_Comodos INT,
    ID_Categoria INT,
    ID_Localidade INT,
    ID_Venda INT,
    FOREIGN KEY (ID_Categoria) REFERENCES TP_CATEGORIA(ID_Categoria),
    FOREIGN KEY (ID_Localidade) REFERENCES TP_LOCALIDADE(ID_Localidade),
    FOREIGN KEY (ID_Venda) REFERENCES TP_VENDA(ID_Venda)
);

CREATE TABLE TP_IMAGENS (
    ID_Imagem INT AUTO_INCREMENT PRIMARY KEY,
    Caminho_Imagem VARCHAR(255),
    ID_Item INT,
    FOREIGN KEY (ID_Item) REFERENCES ITENS(ID_Item)
);
