CREATE DATABASE GREENHOUSE;

-- UTILIZANDO O BD
USE GREENHOUSE;

-- CRIANDO UMA TABELA
CREATE TABLE `GREENHOUSE`.`PLANTS`(
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `SENSOR_LEVEL` CHAR(5) DEFAULT NULL,
    PRIMARY KEY `PK_PLANT_NAME` (`PLANT_NAME`)
);

-- COMANDOS DML DE INSERÇÃO DE DADOS
INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Orquidea', 10, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Samambaia', 11, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Babosa', 9, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Palmeira', 15, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Coqueiro', 25, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Pinheiro', 25, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Canhamo', 420, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Girassol', 2, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Violeta', 666, 'MED');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('Mandioca', 51, 'LOW');

-- EXECUTANDO COMANDOS DQL
-- CONSULTANDO TUDO DA TABELA
SELECT * FROM `GREENHOUSE`.`PLANTS`;

-- ESPECIFICANDO APENAS AS COLUNAS DESEJADAS
SELECT PLANT_NAME, SENSOR_EVENT FROM PLANTS;

-- APLICAR FILTROS NOS REGISTROS DE DADOS
SELECT * FROM PLANTS 
WHERE SENSOR_LEVEL = 'HIGH' AND 
SENSOR_VALUE >= 10 AND SENSOR_VALUE <= 20;

SELECT * FROM PLANTS 
WHERE SENSOR_LEVEL IN ('HIGH', 'LOW');

-- CLÁUSULA DE ORDENAÇÃO 
SELECT * FROM PLANTS 
WHERE SENSOR_VALUE < 420 
ORDER BY SENSOR_VALUE DESC;

-- FUNÇÕES DE AGRUPAMENTO
SELECT COUNT(*), SENSOR_LEVEL FROM PLANTS 
GROUP BY SENSOR_LEVEL;

-- SELECT USANDO LIMIT: RETORNA UM NÚMERO ESPECÍFICO DE LINHAS DA TABELA
SELECT * FROM PLANTS
LIMIT 5;

-- MIN E MAX: MIN(COLUNA) RETORNA O MENOR VALOR DA COLUNA; MAX(COLUNA) RETORNA O MAIOR VALOR DA COLUNA
SELECT MIN(SENSOR_VALUE), MAX(SENSOR_VALUE)
FROM PLANTS;

-- SUM(COLUNA): RETORNA A SOMA DOS VALORES DE UMA COLUNA NUMÉRICA ESPECIFICADA
SELECT SUM(SENSOR_VALUE)
FROM PLANTS;

-- SUBQUERY COM SUM()
SELECT SUM(AUX.SENSOR_VALUE)
FROM (
	SELECT SENSOR_VALUE FROM PLANTS
	ORDER BY SENSOR_VALUE ASC
	LIMIT 3
    ) AS AUX;

-- AVG(COLUNA): RETORNA A MÉDIA DOS VALORES NUMÉRICOS DA COLUNA ESPECIFICADA
SELECT AVG(SENSOR_VALUE)
FROM PLANTS;

-- LIKE OPERATOR: USADO COMO OPERADOR NA CLÁUSULA WHERE PARA RETORNAR UM PADRÃO ESPECÍFICO DE STRINGS NUMA COLUNA ESPECÍFICA
-- '%' REPRESENTA 0, 1 OU MAIS CARACTÉRES; '_' REPRESENTA SOMENTE 1 CARACTÉRE
-- EXEMPLO 1: CONTÉM A LETRA 'A' NO NOME
SELECT * FROM PLANTS
WHERE PLANT_NAME LIKE '%A%';

-- EXEMPLO 2: COMEÇA COM A LETRA 'S'
SELECT * FROM PLANTS
WHERE PLANT_NAME LIKE 'S%';

-- EXEMPLO 3: TERMINA COM A LETRA 'A'
SELECT * FROM PLANTS
WHERE PLANT_NAME LIKE '%A';

-- EXEMPLO 4: CONTÉM 'QU' NA PALAVRA
SELECT * FROM PLANTS
WHERE PLANT_NAME LIKE '%QU%';

-- COMANDO UPDATE PARA ATUALIZAR REGISTROS DE DADOS
SELECT * FROM PLANTS;

UPDATE PLANTS 
SET SENSOR_VALUE = 90, SENSOR_LEVEL = 'HIGH'
WHERE PLANT_NAME = 'Babosa';

-- APAGANDO REGISTROS DA TABELA DO BANCO DE DADOS
DELETE FROM PLANTS
WHERE PLANT_NAME = 'Coqueiro';

